"""empty message

Revision ID: 02e721de225f
Revises: 07dc9233fbdf
Create Date: 2026-06-04 01:55:10.554109

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel



# revision identifiers, used by Alembic.
revision: str = '02e721de225f'
down_revision: Union[str, Sequence[str], None] = '07dc9233fbdf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('playervalue',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('site_user_id', sa.UUID(), nullable=False),
    sa.Column('player_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('custom_market_value', sa.Float(), nullable=False),
    sa.Column('notes', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['player_id'], ['player.player_id'], ),
    sa.ForeignKeyConstraint(['site_user_id'], ['siteuser.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_playervalue_player_id'), 'playervalue', ['player_id'], unique=False)
    op.create_index(op.f('ix_playervalue_site_user_id'), 'playervalue', ['site_user_id'], unique=False)
    op.create_table('sleeperconnection',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sleeper_user_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('encrypted_token', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('site_user_id', sa.UUID(), nullable=True),
    sa.Column('session_id', sa.Integer(), nullable=True),
    sa.Column('source', sa.Enum('SESSION', 'USER', name='connectionsource'), nullable=False),
    sa.Column('linked_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['usersession.id'], ),
    sa.ForeignKeyConstraint(['site_user_id'], ['siteuser.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sleeperconnection_session_id'), 'sleeperconnection', ['session_id'], unique=False)
    op.create_index(op.f('ix_sleeperconnection_site_user_id'), 'sleeperconnection', ['site_user_id'], unique=False)
    op.create_index(op.f('ix_sleeperconnection_sleeper_user_id'), 'sleeperconnection', ['sleeper_user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sleeperconnection_sleeper_user_id'), table_name='sleeperconnection')
    op.drop_index(op.f('ix_sleeperconnection_site_user_id'), table_name='sleeperconnection')
    op.drop_index(op.f('ix_sleeperconnection_session_id'), table_name='sleeperconnection')
    op.drop_table('sleeperconnection')
    op.drop_index(op.f('ix_playervalue_site_user_id'), table_name='playervalue')
    op.drop_index(op.f('ix_playervalue_player_id'), table_name='playervalue')
    op.drop_table('playervalue')
    # ### end Alembic commands ###
