"""empty message

Revision ID: 07dc9233fbdf
Revises: 663547400e2e
Create Date: 2026-06-04 01:37:37.170345

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel



# revision identifiers, used by Alembic.
revision: str = '07dc9233fbdf'
down_revision: Union[str, Sequence[str], None] = '663547400e2e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_siteuser_sleeper_id'), table_name='siteuser')
    op.drop_column('siteuser', 'sleeper_id')
    op.drop_column('siteuser', 'encrypted_sleeper_token')
    op.alter_column('usersession', 'site_user_id',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('usersession', 'site_user_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.add_column('siteuser', sa.Column('encrypted_sleeper_token', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('siteuser', sa.Column('sleeper_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.create_index(op.f('ix_siteuser_sleeper_id'), 'siteuser', ['sleeper_id'], unique=False)
    # ### end Alembic commands ###
