"""empty message

Revision ID: 197ff57fbef9
Revises: 4b38eb7217ee
Create Date: 2026-05-16 21:00:32.062997

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel



# revision identifiers, used by Alembic.
revision: str = '197ff57fbef9'
down_revision: Union[str, Sequence[str], None] = '4b38eb7217ee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_movement_roster_tx', 'movement', ['roster_id', 'transaction_id'], unique=False)
    op.create_index('idx_roster_owner_league', 'roster', ['owner_id', 'league_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_roster_owner_league', table_name='roster')
    op.drop_index('idx_movement_roster_tx', table_name='movement')
    # ### end Alembic commands ###
