"""empty message

Revision ID: 1feeeb6c4628
Revises: 9e4ec89deba2
Create Date: 2026-06-29 22:44:32.879097

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel



# revision identifiers, used by Alembic.
revision: str = '1feeeb6c4628'
down_revision: Union[str, Sequence[str], None] = '9e4ec89deba2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('playerprojection', 'scoring_format')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('playerprojection', sa.Column('scoring_format', sa.VARCHAR(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
