"""empty message

Revision ID: 217e845e755f
Revises: 3869467e5399
Create Date: 2026-06-30 16:21:40.565356

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel



# revision identifiers, used by Alembic.
revision: str = '217e845e755f'
down_revision: Union[str, Sequence[str], None] = '3869467e5399'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ktcplayermap',
    sa.Column('ktc_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('player_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('matched_via', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['player_id'], ['player.player_id'], ),
    sa.PrimaryKeyConstraint('ktc_name')
    )
    op.create_index(op.f('ix_ktcplayermap_player_id'), 'ktcplayermap', ['player_id'], unique=False)
    op.create_table('ktcvalue',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('player_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('value', sa.Integer(), nullable=False),
    sa.Column('position_rank', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('sf_value', sa.Integer(), nullable=True),
    sa.Column('sf_position_rank', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('redraft_value', sa.Integer(), nullable=True),
    sa.Column('redraft_position_rank', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('sf_redraft_value', sa.Integer(), nullable=True),
    sa.Column('sf_redraft_position_rank', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['player_id'], ['player.player_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('player_id', name='uq_ktc_value_player')
    )
    op.create_index(op.f('ix_ktcvalue_player_id'), 'ktcvalue', ['player_id'], unique=False)
    op.create_table('underdogadp',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('player_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('slate_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('scoring_type_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('superflex', sa.Boolean(), nullable=False),
    sa.Column('adp', sa.Float(), nullable=False),
    sa.Column('position_rank', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('avg_weekly_points', sa.Float(), nullable=True),
    sa.Column('salary', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['player_id'], ['player.player_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('player_id', 'slate_id', 'scoring_type_id', name='uq_underdog_adp_player_slate')
    )
    op.create_index('idx_underdog_adp_superflex', 'underdogadp', ['superflex'], unique=False)
    op.create_index(op.f('ix_underdogadp_player_id'), 'underdogadp', ['player_id'], unique=False)
    op.create_index(op.f('ix_underdogadp_scoring_type_id'), 'underdogadp', ['scoring_type_id'], unique=False)
    op.create_index(op.f('ix_underdogadp_slate_id'), 'underdogadp', ['slate_id'], unique=False)
    op.create_index(op.f('ix_underdogadp_superflex'), 'underdogadp', ['superflex'], unique=False)
    op.create_table('underdogplayermap',
    sa.Column('underdog_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('player_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('matched_via', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['player_id'], ['player.player_id'], ),
    sa.PrimaryKeyConstraint('underdog_id')
    )
    op.create_index(op.f('ix_underdogplayermap_player_id'), 'underdogplayermap', ['player_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_underdogplayermap_player_id'), table_name='underdogplayermap')
    op.drop_table('underdogplayermap')
    op.drop_index(op.f('ix_underdogadp_superflex'), table_name='underdogadp')
    op.drop_index(op.f('ix_underdogadp_slate_id'), table_name='underdogadp')
    op.drop_index(op.f('ix_underdogadp_scoring_type_id'), table_name='underdogadp')
    op.drop_index(op.f('ix_underdogadp_player_id'), table_name='underdogadp')
    op.drop_index('idx_underdog_adp_superflex', table_name='underdogadp')
    op.drop_table('underdogadp')
    op.drop_index(op.f('ix_ktcvalue_player_id'), table_name='ktcvalue')
    op.drop_table('ktcvalue')
    op.drop_index(op.f('ix_ktcplayermap_player_id'), table_name='ktcplayermap')
    op.drop_table('ktcplayermap')
    # ### end Alembic commands ###
