"""add_roster_composite_unique_constraint

Revision ID: 21d0a451a0d8
Revises: 9dde64709ea0
Create Date: 2026-05-16 18:58:27.063744

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel



# revision identifiers, used by Alembic.
revision: str = '21d0a451a0d8'
down_revision: Union[str, Sequence[str], None] = '9dde64709ea0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_roster_league_roster_id', 'roster', ['league_id', 'roster_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_roster_league_roster_id', 'roster', type_='unique')
    # ### end Alembic commands ###
