"""empty message

Revision ID: 271cd2ad165b
Revises: fff6cbd37207
Create Date: 2026-06-29 19:18:18.164166

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel



# revision identifiers, used by Alembic.
revision: str = '271cd2ad165b'
down_revision: Union[str, Sequence[str], None] = 'fff6cbd37207'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade():
    op.add_column(
        "playerprojection",
        sa.Column(
            "games_played",
            sa.Float(),
            nullable=False,
            server_default="17",
        ),
    )

    op.alter_column(
        "playerprojection",
        "games_played",
        server_default=None,
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('playerprojection', 'games_played')
    # ### end Alembic commands ###
