"""empty message

Revision ID: 27715eefe1e2
Revises: 
Create Date: 2026-05-16 18:36:02.885563

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '27715eefe1e2'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('internalstate',
    sa.Column('key', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('value', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('league',
    sa.Column('league_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('total_rosters', sa.Integer(), nullable=False),
    sa.Column('draft_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('avatar', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('season', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('dynasty', sa.Boolean(), nullable=False),
    sa.Column('best_ball', sa.Boolean(), nullable=False),
    sa.Column('trade_deadline', sa.Integer(), nullable=False),
    sa.Column('bonus_rec_te', sa.Integer(), nullable=False),
    sa.Column('rec', sa.Integer(), nullable=False),
    sa.Column('pass_td', sa.Integer(), nullable=False),
    sa.Column('roster_positions', postgresql.ARRAY(sa.String()), nullable=True),
    sa.PrimaryKeyConstraint('league_id')
    )
    op.create_index(op.f('ix_league_draft_id'), 'league', ['draft_id'], unique=True)
    op.create_table('player',
    sa.Column('player_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('position', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('team', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('first_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('last_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('years_exp', sa.Integer(), nullable=False),
    sa.Column('birth_date', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('player_id')
    )
    op.create_index(op.f('ix_player_birth_date'), 'player', ['birth_date'], unique=False)
    op.create_index(op.f('ix_player_first_name'), 'player', ['first_name'], unique=False)
    op.create_index(op.f('ix_player_last_name'), 'player', ['last_name'], unique=False)
    op.create_index(op.f('ix_player_position'), 'player', ['position'], unique=False)
    op.create_index(op.f('ix_player_team'), 'player', ['team'], unique=False)
    op.create_index(op.f('ix_player_years_exp'), 'player', ['years_exp'], unique=False)
    op.create_table('user',
    sa.Column('user_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('display_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('avatar', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('is_owner', sa.Boolean(), nullable=True),
    sa.Column('is_placeholder', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('draft',
    sa.Column('draft_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('league_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('season', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('draft_order', sa.JSON(), nullable=True),
    sa.Column('slot_to_roster_id', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['league_id'], ['league.league_id'], ),
    sa.PrimaryKeyConstraint('draft_id')
    )
    op.create_index(op.f('ix_draft_league_id'), 'draft', ['league_id'], unique=False)
    op.create_index(op.f('ix_draft_season'), 'draft', ['season'], unique=False)
    op.create_table('roster',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('roster_id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('league_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('players', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('fpts', sa.Integer(), nullable=False),
    sa.Column('fpts_against', sa.Integer(), nullable=False),
    sa.Column('wins', sa.Integer(), nullable=False),
    sa.Column('ties', sa.Integer(), nullable=False),
    sa.Column('losses', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['league_id'], ['league.league_id'], ),
    sa.ForeignKeyConstraint(['owner_id'], ['user.user_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sqlite_autoincrement=True
    )
    op.create_index(op.f('ix_roster_league_id'), 'roster', ['league_id'], unique=False)
    op.create_index(op.f('ix_roster_owner_id'), 'roster', ['owner_id'], unique=False)
    op.create_index(op.f('ix_roster_roster_id'), 'roster', ['roster_id'], unique=False)
    op.create_table('transaction',
    sa.Column('transaction_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('time_ms', sa.Integer(), nullable=True),
    sa.Column('league_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['league_id'], ['league.league_id'], ),
    sa.PrimaryKeyConstraint('transaction_id')
    )
    op.create_index(op.f('ix_transaction_league_id'), 'transaction', ['league_id'], unique=False)
    op.create_index(op.f('ix_transaction_time_ms'), 'transaction', ['time_ms'], unique=False)
    op.create_index(op.f('ix_transaction_type'), 'transaction', ['type'], unique=False)
    op.create_table('movement',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('transaction_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('player_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('roster_id', sa.Integer(), nullable=False),
    sa.Column('action', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['transaction_id'], ['transaction.transaction_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_movement_action'), 'movement', ['action'], unique=False)
    op.create_index(op.f('ix_movement_player_id'), 'movement', ['player_id'], unique=False)
    op.create_index(op.f('ix_movement_roster_id'), 'movement', ['roster_id'], unique=False)
    op.create_index(op.f('ix_movement_transaction_id'), 'movement', ['transaction_id'], unique=False)
    op.create_table('tradedpick',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('transaction_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('season', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('round', sa.Integer(), nullable=False),
    sa.Column('new_roster_id', sa.Integer(), nullable=False),
    sa.Column('old_roster_id', sa.Integer(), nullable=False),
    sa.Column('og_roster_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['transaction_id'], ['transaction.transaction_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tradedpick_new_roster_id'), 'tradedpick', ['new_roster_id'], unique=False)
    op.create_index(op.f('ix_tradedpick_og_roster_id'), 'tradedpick', ['og_roster_id'], unique=False)
    op.create_index(op.f('ix_tradedpick_old_roster_id'), 'tradedpick', ['old_roster_id'], unique=False)
    op.create_index(op.f('ix_tradedpick_round'), 'tradedpick', ['round'], unique=False)
    op.create_index(op.f('ix_tradedpick_season'), 'tradedpick', ['season'], unique=False)
    op.create_index(op.f('ix_tradedpick_transaction_id'), 'tradedpick', ['transaction_id'], unique=False)
    op.create_table('waiverbudget',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('transaction_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('sender', sa.Integer(), nullable=False),
    sa.Column('receiver', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['transaction_id'], ['transaction.transaction_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_waiverbudget_receiver'), 'waiverbudget', ['receiver'], unique=False)
    op.create_index(op.f('ix_waiverbudget_sender'), 'waiverbudget', ['sender'], unique=False)
    op.create_index(op.f('ix_waiverbudget_transaction_id'), 'waiverbudget', ['transaction_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_waiverbudget_transaction_id'), table_name='waiverbudget')
    op.drop_index(op.f('ix_waiverbudget_sender'), table_name='waiverbudget')
    op.drop_index(op.f('ix_waiverbudget_receiver'), table_name='waiverbudget')
    op.drop_table('waiverbudget')
    op.drop_index(op.f('ix_tradedpick_transaction_id'), table_name='tradedpick')
    op.drop_index(op.f('ix_tradedpick_season'), table_name='tradedpick')
    op.drop_index(op.f('ix_tradedpick_round'), table_name='tradedpick')
    op.drop_index(op.f('ix_tradedpick_old_roster_id'), table_name='tradedpick')
    op.drop_index(op.f('ix_tradedpick_og_roster_id'), table_name='tradedpick')
    op.drop_index(op.f('ix_tradedpick_new_roster_id'), table_name='tradedpick')
    op.drop_table('tradedpick')
    op.drop_index(op.f('ix_movement_transaction_id'), table_name='movement')
    op.drop_index(op.f('ix_movement_roster_id'), table_name='movement')
    op.drop_index(op.f('ix_movement_player_id'), table_name='movement')
    op.drop_index(op.f('ix_movement_action'), table_name='movement')
    op.drop_table('movement')
    op.drop_index(op.f('ix_transaction_type'), table_name='transaction')
    op.drop_index(op.f('ix_transaction_time_ms'), table_name='transaction')
    op.drop_index(op.f('ix_transaction_league_id'), table_name='transaction')
    op.drop_table('transaction')
    op.drop_index(op.f('ix_roster_roster_id'), table_name='roster')
    op.drop_index(op.f('ix_roster_owner_id'), table_name='roster')
    op.drop_index(op.f('ix_roster_league_id'), table_name='roster')
    op.drop_table('roster')
    op.drop_index(op.f('ix_draft_season'), table_name='draft')
    op.drop_index(op.f('ix_draft_league_id'), table_name='draft')
    op.drop_table('draft')
    op.drop_table('user')
    op.drop_index(op.f('ix_player_years_exp'), table_name='player')
    op.drop_index(op.f('ix_player_team'), table_name='player')
    op.drop_index(op.f('ix_player_position'), table_name='player')
    op.drop_index(op.f('ix_player_last_name'), table_name='player')
    op.drop_index(op.f('ix_player_first_name'), table_name='player')
    op.drop_index(op.f('ix_player_birth_date'), table_name='player')
    op.drop_table('player')
    op.drop_index(op.f('ix_league_draft_id'), table_name='league')
    op.drop_table('league')
    op.drop_table('internalstate')
    # ### end Alembic commands ###
