"""empty message

Revision ID: 27be92a824a5
Revises: d7974c582d62
Create Date: 2026-06-09 02:05:42.103634

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel



# revision identifiers, used by Alembic.
revision: str = '27be92a824a5'
down_revision: Union[str, Sequence[str], None] = 'd7974c582d62'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('sleeperconnection', 'site_user_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_index(op.f('ix_sleeperconnection_session_id'), table_name='sleeperconnection')
    op.drop_index(op.f('ix_sleeperconnection_site_user_id'), table_name='sleeperconnection')
    op.create_index(op.f('ix_sleeperconnection_site_user_id'), 'sleeperconnection', ['site_user_id'], unique=True)
    op.drop_index(op.f('ix_sleeperconnection_sleeper_user_id'), table_name='sleeperconnection')
    op.create_index(op.f('ix_sleeperconnection_sleeper_user_id'), 'sleeperconnection', ['sleeper_user_id'], unique=False)
    op.drop_constraint(op.f('sleeperconnection_session_id_fkey'), 'sleeperconnection', type_='foreignkey')
    op.drop_column('sleeperconnection', 'session_id')
    op.add_column('usersession', sa.Column('sleeper_username', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.alter_column('usersession', 'site_user_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_index(op.f('ix_usersession_site_user_id'), table_name='usersession')
    op.drop_index(op.f('ix_usersession_session_token'), table_name='usersession')
    op.create_index(op.f('ix_usersession_session_token'), 'usersession', ['session_token'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_usersession_session_token'), table_name='usersession')
    op.create_index(op.f('ix_usersession_session_token'), 'usersession', ['session_token'], unique=False)
    op.create_index(op.f('ix_usersession_site_user_id'), 'usersession', ['site_user_id'], unique=False)
    op.alter_column('usersession', 'site_user_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_column('usersession', 'sleeper_username')
    op.add_column('sleeperconnection', sa.Column('session_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('sleeperconnection_session_id_fkey'), 'sleeperconnection', 'usersession', ['session_id'], ['id'])
    op.drop_index(op.f('ix_sleeperconnection_sleeper_user_id'), table_name='sleeperconnection')
    op.create_index(op.f('ix_sleeperconnection_sleeper_user_id'), 'sleeperconnection', ['sleeper_user_id'], unique=True)
    op.drop_index(op.f('ix_sleeperconnection_site_user_id'), table_name='sleeperconnection')
    op.create_index(op.f('ix_sleeperconnection_site_user_id'), 'sleeperconnection', ['site_user_id'], unique=False)
    op.create_index(op.f('ix_sleeperconnection_session_id'), 'sleeperconnection', ['session_id'], unique=False)
    op.alter_column('sleeperconnection', 'site_user_id',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###
