"""empty message

Revision ID: 2cfb27cac728
Revises: ea2731ffad7d
Create Date: 2026-06-09 03:35:44.807362

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel



# revision identifiers, used by Alembic.
revision: str = '2cfb27cac728'
down_revision: Union[str, Sequence[str], None] = 'ea2731ffad7d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('sleeperconnection_site_user_id_fkey'), 'sleeperconnection', type_='foreignkey')
    op.create_foreign_key(None, 'sleeperconnection', 'siteuser', ['site_user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'sleeperconnection', type_='foreignkey')
    op.create_foreign_key(op.f('sleeperconnection_site_user_id_fkey'), 'sleeperconnection', 'siteuser', ['site_user_id'], ['id'])
    # ### end Alembic commands ###
