"""empty message

Revision ID: 3b39a5479b9c
Revises: d520572c1e50
Create Date: 2026-05-21 21:22:03.197171

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel



# revision identifiers, used by Alembic.
revision: str = '3b39a5479b9c'
down_revision: Union[str, Sequence[str], None] = 'd520572c1e50'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('siteuser', sa.Column('sleeper_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.drop_index(op.f('ix_siteuser_linked_sleeper_id'), table_name='siteuser')
    op.create_index(op.f('ix_siteuser_sleeper_id'), 'siteuser', ['sleeper_id'], unique=False)
    op.drop_column('siteuser', 'linked_sleeper_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('siteuser', sa.Column('linked_sleeper_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_siteuser_sleeper_id'), table_name='siteuser')
    op.create_index(op.f('ix_siteuser_linked_sleeper_id'), 'siteuser', ['linked_sleeper_id'], unique=False)
    op.drop_column('siteuser', 'sleeper_id')
    # ### end Alembic commands ###
