"""empty message

Revision ID: 44c5fa54492e
Revises: f2fe5499dbbe
Create Date: 2026-06-09 02:33:18.072727

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel



# revision identifiers, used by Alembic.
revision: str = '44c5fa54492e'
down_revision: Union[str, Sequence[str], None] = 'f2fe5499dbbe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sleeperconnection', sa.Column('session_id', sa.Integer(), nullable=True))
    op.alter_column('sleeperconnection', 'site_user_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_index(op.f('ix_sleeperconnection_site_user_id'), table_name='sleeperconnection')
    op.create_index(op.f('ix_sleeperconnection_site_user_id'), 'sleeperconnection', ['site_user_id'], unique=False)
    op.create_index(op.f('ix_sleeperconnection_session_id'), 'sleeperconnection', ['session_id'], unique=False)
    op.create_foreign_key(None, 'sleeperconnection', 'usersession', ['session_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'sleeperconnection', type_='foreignkey')
    op.drop_index(op.f('ix_sleeperconnection_session_id'), table_name='sleeperconnection')
    op.drop_index(op.f('ix_sleeperconnection_site_user_id'), table_name='sleeperconnection')
    op.create_index(op.f('ix_sleeperconnection_site_user_id'), 'sleeperconnection', ['site_user_id'], unique=True)
    op.alter_column('sleeperconnection', 'site_user_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_column('sleeperconnection', 'session_id')
    # ### end Alembic commands ###
