"""make tradedpick transaction_id nullable

Revision ID: 488ee922f3d6
Revises: 5e0b25f0b64f
Create Date: 2026-07-14 17:15:11.493384

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel



# revision identifiers, used by Alembic.
revision: str = '488ee922f3d6'
down_revision: Union[str, Sequence[str], None] = '5e0b25f0b64f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tradedpick', 'transaction_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tradedpick', 'transaction_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
