"""empty message

Revision ID: 4b38eb7217ee
Revises: c99c6df8c168
Create Date: 2026-05-16 19:07:11.489527

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel



# revision identifiers, used by Alembic.
revision: str = '4b38eb7217ee'
down_revision: Union[str, Sequence[str], None] = 'c99c6df8c168'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('movement', 'roster_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('movement', 'action',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('roster', 'roster_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('roster', 'roster_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('movement', 'action',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('movement', 'roster_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
