"""add_user_league_note

Revision ID: 4ed89f8389c6
Revises: f0a1c9d2e3b4
Create Date: 2026-07-13 23:15:06.899244

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel



# revision identifiers, used by Alembic.
revision: str = '4ed89f8389c6'
down_revision: Union[str, Sequence[str], None] = 'f0a1c9d2e3b4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('userleaguenote',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('site_user_id', sa.UUID(), nullable=False),
    sa.Column('league_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('note', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['league_id'], ['league.league_id'], ),
    sa.ForeignKeyConstraint(['site_user_id'], ['siteuser.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('site_user_id', 'league_id', name='uq_userleaguenote_site_user_league')
    )
    op.create_index(op.f('ix_userleaguenote_league_id'), 'userleaguenote', ['league_id'], unique=False)
    op.create_index(op.f('ix_userleaguenote_site_user_id'), 'userleaguenote', ['site_user_id'], unique=False)
    op.drop_constraint(op.f('financeuserdefaults_site_user_id_key'), 'financeuserdefaults', type_='unique')
    op.create_index(op.f('ix_personalrankcurve_rank_band_end'), 'personalrankcurve', ['rank_band_end'], unique=False)
    op.create_index(op.f('ix_personalrankcurve_rank_band_start'), 'personalrankcurve', ['rank_band_start'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_personalrankcurve_rank_band_start'), table_name='personalrankcurve')
    op.drop_index(op.f('ix_personalrankcurve_rank_band_end'), table_name='personalrankcurve')
    op.create_unique_constraint(op.f('financeuserdefaults_site_user_id_key'), 'financeuserdefaults', ['site_user_id'], postgresql_nulls_not_distinct=False)
    op.drop_index(op.f('ix_userleaguenote_site_user_id'), table_name='userleaguenote')
    op.drop_index(op.f('ix_userleaguenote_league_id'), table_name='userleaguenote')
    op.drop_table('userleaguenote')
    # ### end Alembic commands ###
