"""empty message

Revision ID: 56f3a71dddd1
Revises: 217e845e755f
Create Date: 2026-06-30 18:24:42.865198

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel



# revision identifiers, used by Alembic.
revision: str = '56f3a71dddd1'
down_revision: Union[str, Sequence[str], None] = '217e845e755f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fantasycalcvalue',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('player_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('is_dynasty', sa.Boolean(), nullable=False),
    sa.Column('num_qbs', sa.Integer(), nullable=False),
    sa.Column('num_teams', sa.Integer(), nullable=False),
    sa.Column('ppr', sa.Integer(), nullable=False),
    sa.Column('value', sa.Integer(), nullable=False),
    sa.Column('overall_rank', sa.Integer(), nullable=True),
    sa.Column('position_rank', sa.Integer(), nullable=True),
    sa.Column('trend_30_day', sa.Integer(), nullable=True),
    sa.Column('redraft_value', sa.Integer(), nullable=True),
    sa.Column('combined_value', sa.Integer(), nullable=True),
    sa.Column('tier', sa.Integer(), nullable=True),
    sa.Column('adp', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['player_id'], ['player.player_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('player_id', 'is_dynasty', 'num_qbs', 'num_teams', 'ppr', name='uq_fantasycalc_value_format')
    )
    op.create_index('idx_fantasycalc_value_player', 'fantasycalcvalue', ['player_id'], unique=False)
    op.create_index(op.f('ix_fantasycalcvalue_is_dynasty'), 'fantasycalcvalue', ['is_dynasty'], unique=False)
    op.create_index(op.f('ix_fantasycalcvalue_num_qbs'), 'fantasycalcvalue', ['num_qbs'], unique=False)
    op.create_index(op.f('ix_fantasycalcvalue_num_teams'), 'fantasycalcvalue', ['num_teams'], unique=False)
    op.create_index(op.f('ix_fantasycalcvalue_player_id'), 'fantasycalcvalue', ['player_id'], unique=False)
    op.create_index(op.f('ix_fantasycalcvalue_ppr'), 'fantasycalcvalue', ['ppr'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_fantasycalcvalue_ppr'), table_name='fantasycalcvalue')
    op.drop_index(op.f('ix_fantasycalcvalue_player_id'), table_name='fantasycalcvalue')
    op.drop_index(op.f('ix_fantasycalcvalue_num_teams'), table_name='fantasycalcvalue')
    op.drop_index(op.f('ix_fantasycalcvalue_num_qbs'), table_name='fantasycalcvalue')
    op.drop_index(op.f('ix_fantasycalcvalue_is_dynasty'), table_name='fantasycalcvalue')
    op.drop_index('idx_fantasycalc_value_player', table_name='fantasycalcvalue')
    op.drop_table('fantasycalcvalue')
    # ### end Alembic commands ###
