"""add_usersession_settings_for_theme

Revision ID: 57130f903ddb
Revises: 9b3643b5f9d8
Create Date: 2026-07-10 19:19:15.190372

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel



# revision identifiers, used by Alembic.
revision: str = '57130f903ddb'
down_revision: Union[str, Sequence[str], None] = '9b3643b5f9d8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.add_column(
        'usersession',
        sa.Column('settings', sa.JSON(), nullable=True),
    )

    op.execute("""
        UPDATE usersession
        SET settings = '{}'::json
        WHERE settings IS NULL
    """)

    op.alter_column(
        'usersession',
        'settings',
        nullable=False,
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('usersession', 'settings')
    # ### end Alembic commands ###
