"""add leaguesortorder table

Revision ID: 5e0b25f0b64f
Revises: c2a8d6b9f0e1
Create Date: 2026-07-14 04:36:16.864330

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel



# revision identifiers, used by Alembic.
revision: str = '5e0b25f0b64f'
down_revision: Union[str, Sequence[str], None] = 'c2a8d6b9f0e1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('leaguesortorder',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('league_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['league_id'], ['league.league_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'league_id', name='uq_leaguesortorder_user_league')
    )
    op.create_index(op.f('ix_leaguesortorder_league_id'), 'leaguesortorder', ['league_id'], unique=False)
    op.create_index(op.f('ix_leaguesortorder_user_id'), 'leaguesortorder', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_leaguesortorder_user_id'), table_name='leaguesortorder')
    op.drop_index(op.f('ix_leaguesortorder_league_id'), table_name='leaguesortorder')
    op.drop_table('leaguesortorder')
    # ### end Alembic commands ###
