"""empty message

Revision ID: 663547400e2e
Revises: 3b39a5479b9c
Create Date: 2026-06-02 16:15:47.524414

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel



# revision identifiers, used by Alembic.
revision: str = '663547400e2e'
down_revision: Union[str, Sequence[str], None] = '3b39a5479b9c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_playervalue_player_id'), table_name='playervalue')
    op.drop_index(op.f('ix_playervalue_site_user_id'), table_name='playervalue')
    op.drop_table('playervalue')
    op.add_column('siteuser', sa.Column('encrypted_sleeper_token', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('siteuser', 'encrypted_sleeper_token')
    op.create_table('playervalue',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('site_user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('player_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('custom_market_value', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('notes', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['player_id'], ['player.player_id'], name=op.f('playervalue_player_id_fkey')),
    sa.ForeignKeyConstraint(['site_user_id'], ['siteuser.id'], name=op.f('playervalue_site_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('playervalue_pkey'))
    )
    op.create_index(op.f('ix_playervalue_site_user_id'), 'playervalue', ['site_user_id'], unique=False)
    op.create_index(op.f('ix_playervalue_player_id'), 'playervalue', ['player_id'], unique=False)
    # ### end Alembic commands ###
