"""track full league sync freshness

Revision ID: 771b6bb3cb32
Revises: c47e43c1a357
Create Date: 2026-07-11 20:20:44.447084

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel



# revision identifiers, used by Alembic.
revision: str = '771b6bb3cb32'
down_revision: Union[str, Sequence[str], None] = 'c47e43c1a357'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('leaguesyncstate', sa.Column('last_full_synced_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('leaguesyncstate', 'last_full_synced_at')
    # ### end Alembic commands ###
