"""empty message

Revision ID: 9b3643b5f9d8
Revises: 355019091c50
Create Date: 2026-07-06 04:17:20.028404

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel



# revision identifiers, used by Alembic.
revision: str = '9b3643b5f9d8'
down_revision: Union[str, Sequence[str], None] = '355019091c50'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transaction', sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.create_index(op.f('ix_transaction_status'), 'transaction', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_transaction_status'), table_name='transaction')
    op.drop_column('transaction', 'status')
    # ### end Alembic commands ###
