"""empty message

Revision ID: 9dde64709ea0
Revises: 27715eefe1e2
Create Date: 2026-05-16 18:46:18.624835

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel



# revision identifiers, used by Alembic.
revision: str = '9dde64709ea0'
down_revision: Union[str, Sequence[str], None] = '27715eefe1e2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('league', 'draft_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('league', 'best_ball',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('league', 'trade_deadline',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('player', 'position',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('player', 'team',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('player', 'years_exp',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('player', 'birth_date',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('player', 'birth_date',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('player', 'years_exp',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('player', 'team',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('player', 'position',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('league', 'trade_deadline',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('league', 'best_ball',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('league', 'draft_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
