"""empty message

Revision ID: b0056cf499a3
Revises: 02e721de225f
Create Date: 2026-06-04 03:24:51.689651

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel



# revision identifiers, used by Alembic.
revision: str = 'b0056cf499a3'
down_revision: Union[str, Sequence[str], None] = '02e721de225f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sleeperconnection_sleeper_user_id'), table_name='sleeperconnection')
    op.create_index(op.f('ix_sleeperconnection_sleeper_user_id'), 'sleeperconnection', ['sleeper_user_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sleeperconnection_sleeper_user_id'), table_name='sleeperconnection')
    op.create_index(op.f('ix_sleeperconnection_sleeper_user_id'), 'sleeperconnection', ['sleeper_user_id'], unique=False)
    # ### end Alembic commands ###
