"""add rookie draft selections

Revision ID: b4e2a11dc1be
Revises: d9d556e0049a
Create Date: 2026-07-14 22:23:13.908096

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel



# revision identifiers, used by Alembic.
revision: str = 'b4e2a11dc1be'
down_revision: Union[str, Sequence[str], None] = 'd9d556e0049a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('draftselection',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('draft_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('league_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('season', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('round', sa.Integer(), nullable=False),
    sa.Column('pick_no', sa.Integer(), nullable=False),
    sa.Column('round_slot', sa.Integer(), nullable=False),
    sa.Column('roster_id', sa.Integer(), nullable=True),
    sa.Column('player_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('is_keeper', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['draft_id'], ['draft.draft_id'], ),
    sa.ForeignKeyConstraint(['league_id'], ['league.league_id'], ),
    sa.ForeignKeyConstraint(['player_id'], ['player.player_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('draft_id', 'pick_no', name='uq_draftselection_draft_pick_no')
    )
    op.create_index(op.f('ix_draftselection_draft_id'), 'draftselection', ['draft_id'], unique=False)
    op.create_index(op.f('ix_draftselection_league_id'), 'draftselection', ['league_id'], unique=False)
    op.create_index(op.f('ix_draftselection_pick_no'), 'draftselection', ['pick_no'], unique=False)
    op.create_index(op.f('ix_draftselection_player_id'), 'draftselection', ['player_id'], unique=False)
    op.create_index(op.f('ix_draftselection_roster_id'), 'draftselection', ['roster_id'], unique=False)
    op.create_index(op.f('ix_draftselection_round'), 'draftselection', ['round'], unique=False)
    op.create_index(op.f('ix_draftselection_round_slot'), 'draftselection', ['round_slot'], unique=False)
    op.create_index(op.f('ix_draftselection_season'), 'draftselection', ['season'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_draftselection_season'), table_name='draftselection')
    op.drop_index(op.f('ix_draftselection_round_slot'), table_name='draftselection')
    op.drop_index(op.f('ix_draftselection_round'), table_name='draftselection')
    op.drop_index(op.f('ix_draftselection_roster_id'), table_name='draftselection')
    op.drop_index(op.f('ix_draftselection_player_id'), table_name='draftselection')
    op.drop_index(op.f('ix_draftselection_pick_no'), table_name='draftselection')
    op.drop_index(op.f('ix_draftselection_league_id'), table_name='draftselection')
    op.drop_index(op.f('ix_draftselection_draft_id'), table_name='draftselection')
    op.drop_table('draftselection')
    # ### end Alembic commands ###
