"""empty message

Revision ID: b66ba38de831
Revises: 1feeeb6c4628
Create Date: 2026-06-29 22:58:30.033707

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel



# revision identifiers, used by Alembic.
revision: str = 'b66ba38de831'
down_revision: Union[str, Sequence[str], None] = '1feeeb6c4628'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:

    # Add nullable first
    op.add_column(
        "league",
        sa.Column(
            "settings",
            sa.JSON(),
            nullable=True,
        ),
    )

    op.add_column(
        "league",
        sa.Column(
            "scoring_settings",
            sa.JSON(),
            nullable=True,
        ),
    )


    # Populate existing rows
    op.execute(
        """
        UPDATE league
        SET settings = '{}'::json
        WHERE settings IS NULL
        """
    )

    op.execute(
        """
        UPDATE league
        SET scoring_settings = '{}'::json
        WHERE scoring_settings IS NULL
        """
    )


    # Now enforce not-null if desired
    op.alter_column(
        "league",
        "settings",
        nullable=False,
    )

    op.alter_column(
        "league",
        "scoring_settings",
        nullable=False,
    )


    op.drop_column(
        "league",
        "pass_td",
    )

    op.drop_column(
        "league",
        "trade_deadline",
    )

    op.drop_column(
        "league",
        "bonus_rec_te",
    )

    op.drop_column(
        "league",
        "best_ball",
    )

    op.drop_column(
        "league",
        "rec",
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('league', sa.Column('rec', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.add_column('league', sa.Column('best_ball', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('league', sa.Column('bonus_rec_te', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.add_column('league', sa.Column('trade_deadline', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('league', sa.Column('pass_td', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.drop_column('league', 'scoring_settings')
    op.drop_column('league', 'settings')
    # ### end Alembic commands ###
