"""empty message

Revision ID: c11238068b22
Revises: e968bf997614
Create Date: 2026-06-29 00:54:36.064430

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel



# revision identifiers, used by Alembic.
revision: str = 'c11238068b22'
down_revision: Union[str, Sequence[str], None] = 'e968bf997614'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('playerprojection',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('player_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('season', sa.Integer(), nullable=False),
    sa.Column('source', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('scoring_format', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('projected_points', sa.Float(), nullable=False),
    sa.Column('projected_ppg', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['player_id'], ['player.player_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_playerprojection_player_id'), 'playerprojection', ['player_id'], unique=False)
    op.create_index(op.f('ix_playerprojection_season'), 'playerprojection', ['season'], unique=False)
    op.create_index(op.f('ix_playerprojection_source'), 'playerprojection', ['source'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_playerprojection_source'), table_name='playerprojection')
    op.drop_index(op.f('ix_playerprojection_season'), table_name='playerprojection')
    op.drop_index(op.f('ix_playerprojection_player_id'), table_name='playerprojection')
    op.drop_table('playerprojection')
    # ### end Alembic commands ###
