"""add pick value tables

Revision ID: c47e43c1a357
Revises: 57130f903ddb
Create Date: 2026-07-11 02:19:39.436915

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel



# revision identifiers, used by Alembic.
revision: str = 'c47e43c1a357'
down_revision: Union[str, Sequence[str], None] = '57130f903ddb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fantasycalcpickvalue',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('source_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('season', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('round', sa.Integer(), nullable=False),
    sa.Column('slot', sa.Integer(), nullable=True),
    sa.Column('is_exact_slot', sa.Boolean(), nullable=False),
    sa.Column('is_dynasty', sa.Boolean(), nullable=False),
    sa.Column('num_qbs', sa.Integer(), nullable=False),
    sa.Column('num_teams', sa.Integer(), nullable=False),
    sa.Column('ppr', sa.Integer(), nullable=False),
    sa.Column('value', sa.Integer(), nullable=False),
    sa.Column('overall_rank', sa.Integer(), nullable=True),
    sa.Column('position_rank', sa.Integer(), nullable=True),
    sa.Column('trend_30_day', sa.Integer(), nullable=True),
    sa.Column('redraft_value', sa.Integer(), nullable=True),
    sa.Column('combined_value', sa.Integer(), nullable=True),
    sa.Column('tier', sa.Integer(), nullable=True),
    sa.Column('adp', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_id', 'is_dynasty', 'num_qbs', 'num_teams', 'ppr', name='uq_fantasycalc_pick_value_source_format')
    )
    op.create_index('idx_fantasycalc_pick_value_lookup', 'fantasycalcpickvalue', ['season', 'round', 'slot', 'is_dynasty', 'num_qbs', 'num_teams', 'ppr'], unique=False)
    op.create_index(op.f('ix_fantasycalcpickvalue_is_dynasty'), 'fantasycalcpickvalue', ['is_dynasty'], unique=False)
    op.create_index(op.f('ix_fantasycalcpickvalue_is_exact_slot'), 'fantasycalcpickvalue', ['is_exact_slot'], unique=False)
    op.create_index(op.f('ix_fantasycalcpickvalue_num_qbs'), 'fantasycalcpickvalue', ['num_qbs'], unique=False)
    op.create_index(op.f('ix_fantasycalcpickvalue_num_teams'), 'fantasycalcpickvalue', ['num_teams'], unique=False)
    op.create_index(op.f('ix_fantasycalcpickvalue_ppr'), 'fantasycalcpickvalue', ['ppr'], unique=False)
    op.create_index(op.f('ix_fantasycalcpickvalue_round'), 'fantasycalcpickvalue', ['round'], unique=False)
    op.create_index(op.f('ix_fantasycalcpickvalue_season'), 'fantasycalcpickvalue', ['season'], unique=False)
    op.create_index(op.f('ix_fantasycalcpickvalue_slot'), 'fantasycalcpickvalue', ['slot'], unique=False)
    op.create_index(op.f('ix_fantasycalcpickvalue_source_id'), 'fantasycalcpickvalue', ['source_id'], unique=False)
    op.create_index(op.f('ix_fantasycalcpickvalue_source_name'), 'fantasycalcpickvalue', ['source_name'], unique=False)
    op.create_table('ktcpickvalue',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('season', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('round', sa.Integer(), nullable=False),
    sa.Column('bucket', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('value', sa.Integer(), nullable=False),
    sa.Column('sf_value', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('season', 'round', 'bucket', name='uq_ktc_pick_value_shape')
    )
    op.create_index('idx_ktc_pick_value_lookup', 'ktcpickvalue', ['season', 'round', 'bucket'], unique=False)
    op.create_index(op.f('ix_ktcpickvalue_bucket'), 'ktcpickvalue', ['bucket'], unique=False)
    op.create_index(op.f('ix_ktcpickvalue_round'), 'ktcpickvalue', ['round'], unique=False)
    op.create_index(op.f('ix_ktcpickvalue_season'), 'ktcpickvalue', ['season'], unique=False)
    op.create_index(op.f('ix_ktcpickvalue_source_name'), 'ktcpickvalue', ['source_name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ktcpickvalue_source_name'), table_name='ktcpickvalue')
    op.drop_index(op.f('ix_ktcpickvalue_season'), table_name='ktcpickvalue')
    op.drop_index(op.f('ix_ktcpickvalue_round'), table_name='ktcpickvalue')
    op.drop_index(op.f('ix_ktcpickvalue_bucket'), table_name='ktcpickvalue')
    op.drop_index('idx_ktc_pick_value_lookup', table_name='ktcpickvalue')
    op.drop_table('ktcpickvalue')
    op.drop_index(op.f('ix_fantasycalcpickvalue_source_name'), table_name='fantasycalcpickvalue')
    op.drop_index(op.f('ix_fantasycalcpickvalue_source_id'), table_name='fantasycalcpickvalue')
    op.drop_index(op.f('ix_fantasycalcpickvalue_slot'), table_name='fantasycalcpickvalue')
    op.drop_index(op.f('ix_fantasycalcpickvalue_season'), table_name='fantasycalcpickvalue')
    op.drop_index(op.f('ix_fantasycalcpickvalue_round'), table_name='fantasycalcpickvalue')
    op.drop_index(op.f('ix_fantasycalcpickvalue_ppr'), table_name='fantasycalcpickvalue')
    op.drop_index(op.f('ix_fantasycalcpickvalue_num_teams'), table_name='fantasycalcpickvalue')
    op.drop_index(op.f('ix_fantasycalcpickvalue_num_qbs'), table_name='fantasycalcpickvalue')
    op.drop_index(op.f('ix_fantasycalcpickvalue_is_exact_slot'), table_name='fantasycalcpickvalue')
    op.drop_index(op.f('ix_fantasycalcpickvalue_is_dynasty'), table_name='fantasycalcpickvalue')
    op.drop_index('idx_fantasycalc_pick_value_lookup', table_name='fantasycalcpickvalue')
    op.drop_table('fantasycalcpickvalue')
    # ### end Alembic commands ###
