"""empty message

Revision ID: c99c6df8c168
Revises: de5d9f41269a
Create Date: 2026-05-16 19:02:10.701224

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel



# revision identifiers, used by Alembic.
revision: str = 'c99c6df8c168'
down_revision: Union[str, Sequence[str], None] = 'de5d9f41269a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('movement', 'player_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('movement', 'player_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
