"""empty message

Revision ID: cc303ae0aadb
Revises: 56f3a71dddd1
Create Date: 2026-07-04 04:45:06.756873

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel



# revision identifiers, used by Alembic.
revision: str = 'cc303ae0aadb'
down_revision: Union[str, Sequence[str], None] = '56f3a71dddd1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('leaguesyncstate',
    sa.Column('league_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('last_synced_week', sa.Integer(), nullable=False),
    sa.Column('last_synced_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['league_id'], ['league.league_id'], ),
    sa.PrimaryKeyConstraint('league_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('leaguesyncstate')
    # ### end Alembic commands ###
