"""empty message

Revision ID: d7974c582d62
Revises: 82194f39be0b
Create Date: 2026-06-09 01:12:50.804241

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd7974c582d62'
down_revision: Union[str, Sequence[str], None] = '82194f39be0b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sleeperconnection', 'source')
    op.alter_column('usersession', 'site_user_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.create_index(op.f('ix_usersession_site_user_id'), 'usersession', ['site_user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_usersession_site_user_id'), table_name='usersession')
    op.alter_column('usersession', 'site_user_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.add_column('sleeperconnection', sa.Column('source', postgresql.ENUM('SESSION', 'USER', name='connectionsource'), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
