"""alter_transaction_time_ms_to_bigint

Revision ID: de5d9f41269a
Revises: 21d0a451a0d8
Create Date: 2026-05-16 18:59:58.334716

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel



# revision identifiers, used by Alembic.
revision: str = 'de5d9f41269a'
down_revision: Union[str, Sequence[str], None] = '21d0a451a0d8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('transaction', 'time_ms',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               nullable=False)
    op.drop_index(op.f('ix_transaction_time_ms'), table_name='transaction')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_transaction_time_ms'), 'transaction', ['time_ms'], unique=False)
    op.alter_column('transaction', 'time_ms',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
