"""empty message

Revision ID: e968bf997614
Revises: 2cfb27cac728
Create Date: 2026-06-27 03:26:54.079508

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel



# revision identifiers, used by Alembic.
revision: str = 'e968bf997614'
down_revision: Union[str, Sequence[str], None] = '2cfb27cac728'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sleeperconnection', sa.Column('sleeper_username', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.create_index(op.f('ix_sleeperconnection_sleeper_username'), 'sleeperconnection', ['sleeper_username'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sleeperconnection_sleeper_username'), table_name='sleeperconnection')
    op.drop_column('sleeperconnection', 'sleeper_username')
    # ### end Alembic commands ###
