"""empty message

Revision ID: ea2731ffad7d
Revises: 6d75d3d3a12a
Create Date: 2026-06-09 03:33:39.865756

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel



# revision identifiers, used by Alembic.
revision: str = 'ea2731ffad7d'
down_revision: Union[str, Sequence[str], None] = '6d75d3d3a12a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('sleeperconnection_session_id_fkey'), 'sleeperconnection', type_='foreignkey')
    op.create_foreign_key(None, 'sleeperconnection', 'usersession', ['session_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'sleeperconnection', type_='foreignkey')
    op.create_foreign_key(op.f('sleeperconnection_session_id_fkey'), 'sleeperconnection', 'usersession', ['session_id'], ['id'])
    # ### end Alembic commands ###
