"""empty message

Revision ID: eb87ae39e76d
Revises: 05f571ef444c
Create Date: 2026-07-05 19:29:13.734316

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'eb87ae39e76d'
down_revision: Union[str, Sequence[str], None] = '05f571ef444c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""

    # ----------------------------
    # LEAGUE CHANGES
    # ----------------------------

    op.add_column(
        'league',
        sa.Column('status', sa.String(), nullable=True)
    )

    op.add_column(
        'league',
        sa.Column('previous_league_id', sa.String(), nullable=True)
    )

    op.add_column(
        'league',
        sa.Column('league_metadata', sa.JSON(), nullable=True)
    )

    op.create_index(
        op.f('ix_league_previous_league_id'),
        'league',
        ['previous_league_id'],
        unique=False
    )

    op.create_index(
        op.f('ix_league_status'),
        'league',
        ['status'],
        unique=False
    )

    # Backfill existing data (IMPORTANT FIX)
    op.execute("""
        UPDATE league
        SET status = 'in_season'
        WHERE status IS NULL
    """)

    op.execute("""
        UPDATE league
        SET league_metadata = '{}'::json
        WHERE league_metadata IS NULL
    """)

    # Now enforce NOT NULL safely
    op.alter_column('league', 'status', nullable=False)
    op.alter_column('league', 'league_metadata', nullable=False)

    op.drop_column('league', 'dynasty')


    # ----------------------------
    # PLAYER CHANGES
    # ----------------------------

    op.add_column(
        'player',
        sa.Column('status', sa.String(), nullable=True)
    )

    op.add_column(
        'player',
        sa.Column('injury_status', sa.String(), nullable=True)
    )

    op.add_column(
        'player',
        sa.Column('injury_body_part', sa.String(), nullable=True)
    )

    op.add_column(
        'player',
        sa.Column('active', sa.Boolean(), nullable=True)
    )

    op.create_index(
        op.f('ix_player_status'),
        'player',
        ['status'],
        unique=False
    )

    # Backfill player active safely
    op.execute("""
        UPDATE player
        SET active = TRUE
        WHERE active IS NULL
    """)

    op.alter_column('player', 'active', nullable=False)


    # ----------------------------
    # ROSTER CHANGES
    # ----------------------------

    op.add_column(
        'roster',
        sa.Column('starters', postgresql.ARRAY(sa.String()), nullable=True)
    )

    op.add_column(
        'roster',
        sa.Column('reserve', postgresql.ARRAY(sa.String()), nullable=True)
    )

    op.add_column(
        'roster',
        sa.Column('taxi', postgresql.ARRAY(sa.String()), nullable=True)
    )

    op.add_column(
        'roster',
        sa.Column('roster_metadata', sa.JSON(), nullable=True)
    )

    op.add_column(
        'roster',
        sa.Column('settings', sa.JSON(), nullable=True)
    )

    # Backfill JSON fields
    op.execute("""
        UPDATE roster
        SET roster_metadata = '{}'::json
        WHERE roster_metadata IS NULL
    """)

    op.execute("""
        UPDATE roster
        SET settings = '{}'::json
        WHERE settings IS NULL
    """)

    op.alter_column('roster', 'roster_metadata', nullable=False)
    op.alter_column('roster', 'settings', nullable=False)

    op.alter_column(
        'roster',
        'roster_id',
        existing_type=sa.INTEGER(),
        nullable=False
    )

    # Drop old columns
    op.drop_column('roster', 'losses')
    op.drop_column('roster', 'wins')
    op.drop_column('roster', 'ties')
    op.drop_column('roster', 'fpts_against')
    op.drop_column('roster', 'fpts')


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('roster', sa.Column('fpts', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('roster', sa.Column('fpts_against', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('roster', sa.Column('ties', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('roster', sa.Column('wins', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('roster', sa.Column('losses', sa.INTEGER(), autoincrement=False, nullable=False))
    op.alter_column('roster', 'roster_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('roster', 'settings')
    op.drop_column('roster', 'roster_metadata')
    op.drop_column('roster', 'taxi')
    op.drop_column('roster', 'reserve')
    op.drop_column('roster', 'starters')
    op.drop_index(op.f('ix_player_status'), table_name='player')
    op.drop_column('player', 'active')
    op.drop_column('player', 'injury_body_part')
    op.drop_column('player', 'injury_status')
    op.drop_column('player', 'status')
    op.add_column('league', sa.Column('dynasty', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_league_status'), table_name='league')
    op.drop_index(op.f('ix_league_previous_league_id'), table_name='league')
    op.drop_column('league', 'league_metadata')
    op.drop_column('league', 'previous_league_id')
    op.drop_column('league', 'status')
    # ### end Alembic commands ###
