import { describe, expect, it } from 'vitest';

import type { LeagueRoster } from '@/types';

import { buildRosterConstructionRows } from './rosterConstruction';

const roster: LeagueRoster = {
  roster_id: 1,
  owner: {
    user_id: 'user-1',
    display_name: 'Alpha',
    avatar: null,
  },
  rank: 1,
  record: '0-0',
  wins: 0,
  losses: 0,
  ties: 0,
  actual_points_for: 0,
  projected_points: 0,
  faab_remaining: 100,
  waiver_position: 1,
  total_moves: 0,
  open_roster_spots: 0,
  average_age: null,
  total_ktc_value: 0,
  total_fc_value: 0,
  total_redraft_starter_war: 0,
  total_redraft_roster_war: 0,
  total_dynasty_starter_war: 0,
  total_dynasty_roster_war: 0,
  total_pick_ktc_value: 0,
  total_pick_fc_value: 0,
  total_pick_rookie_war_value: 0,
  total_asset_ktc_value: 0,
  total_asset_fc_value: 0,
  picks: [],
  players: [
    {
      player_id: 'qb-1',
      name: 'QB One',
      position: 'QB',
      team: 'KC',
      age: 28,
      underdog_position_rank: null,
      projected_points: null,
      ktc_value: null,
      fc_value: null,
      fc_trend_30_day: null,
      redraft_starter_war: null,
      redraft_roster_war: null,
      dynasty_starter_war: null,
      dynasty_roster_war: 4,
      is_starter: true,
    },
    {
      player_id: 'qb-2',
      name: 'QB Two',
      position: 'QB',
      team: 'ATL',
      age: 24,
      underdog_position_rank: null,
      projected_points: null,
      ktc_value: null,
      fc_value: null,
      fc_trend_30_day: null,
      redraft_starter_war: null,
      redraft_roster_war: null,
      dynasty_starter_war: null,
      dynasty_roster_war: 3,
      is_starter: false,
    },
    {
      player_id: 'rb-1',
      name: 'RB One',
      position: 'RB',
      team: 'DET',
      age: 23,
      underdog_position_rank: null,
      projected_points: null,
      ktc_value: null,
      fc_value: null,
      fc_trend_30_day: null,
      redraft_starter_war: null,
      redraft_roster_war: null,
      dynasty_starter_war: null,
      dynasty_roster_war: 2,
      is_starter: true,
    },
    {
      player_id: 'wr-1',
      name: 'WR One',
      position: 'WR',
      team: 'MIN',
      age: 25,
      underdog_position_rank: null,
      projected_points: null,
      ktc_value: null,
      fc_value: null,
      fc_trend_30_day: null,
      redraft_starter_war: null,
      redraft_roster_war: null,
      dynasty_starter_war: null,
      dynasty_roster_war: 1,
      is_starter: true,
    },
  ],
};

describe('buildRosterConstructionRows', () => {
  it('anchors targets to lineup demand before blending in WAR', () => {
    expect(
      buildRosterConstructionRows(
        roster,
        ['QB', 'RB', 'WR', 'REC_FLEX'],
      ),
    ).toEqual([
      {
        position: 'QB',
        playerCount: 2,
        targetCount: 1.6,
        delta: 0.4,
        warShare: 70,
      },
      {
        position: 'RB',
        playerCount: 1,
        targetCount: 1.4,
        delta: -0.4,
        warShare: 20,
      },
      {
        position: 'WR',
        playerCount: 1,
        targetCount: 1.5,
        delta: -0.4,
        warShare: 10,
      },
      {
        position: 'TE',
        playerCount: 0,
        targetCount: 0.2,
        delta: -0.2,
        warShare: 0,
      },
    ]);
  });
});
